---
name: cppcheck
description: Static analysis of C and C++ code
homepage: https://github.com/danmar/cppcheck
licenses:
  - GPLv3
languages:
  - C++
  - C
categories:
  - Linter
source:
  id: pkg:github/danmar/cppcheck@2.13.0
  build:
    - target: unix
      run: |
        cmake -S . -B build -D USE_MATCHCCOMPILER=ON
        cmake --build build
      bin: build/bin/cppcheck
    - target: win
      run: |
        cmake -S . -B build -D USE_MATCHCCOMPILER=ON
        cmake --build build
      bin: build/bin/cppcheck.exe
bin:
  cppcheck: "{{source.build.bin}}"
